{% set name = "maite" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maite-{{ version }}.tar.gz
  sha256: b076f5890fe37656e8eaedfdc07aa91e35eb180df767cdead4260f985bd1b94c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - poetry-core >=2.0.0,<3.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions >=4.5,!=4.6
    - numpy >=1.24
  run_constrained:
    - pytorch >=1.7,!=1.12.0
    - pyright >=1.1.280,!=1.1.401

test:
  imports:
    - maite
  requires:
    - pip
    - jupytext >=1.14.0
    - numpydoc >=1.5.0
    - pyright >=1.1.280
    - pytest >=7.0.0
    - hypothesis >=6.61.0,<=6.113
    - pytest-mock >=3.10.0
    - pytorch >=1.7,!=1.12.0
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/mit-ll-ai-technology/maite
  summary: Library of common types, protocols (a.k.a. structural subtypes), and utilities to support AI test and evaluation
  dev_url: https://github.com/mit-ll-ai-technology/maite
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jdarena66
    - leihamilton
    - myeesw
