{% set name = "maite" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/maite-{{ version }}.tar.gz
  sha256: 9b68cce74e898b8b5dca99f7a1c5ccf0c083349842ab3670572ab1e19e47608c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=35.0.2
    - wheel >=0.29.0
    - setuptools-scm ==7.0.5
    - pip
  run:
    - python >=3.8
    - typing-extensions >=4.5,!=4.6
    - numpy >=1.17
    - pytorch >=1.7,!=1.12.0

test:
  imports:
    - maite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mit-ll-ai-technology/maite
  summary: Library of common types, protocols (a.k.a. structural subtypes), and utilities to support AI test and evaluation
  dev_url: https://github.com/mit-ll-ai-technology/maite
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jdarena66
    - leihamilton
    - myeesw
