{% set name = "maite" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maite-{{ version }}.tar.gz
  sha256: d3e77f348c178f6e94f76399ee336ccaf71dac89293b9539c550d069e99e1388

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=35.0.2
    - wheel >=0.29.0
    - setuptools-scm ==7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions >=4.5,!=4.6
    - numpy >=1.17,<2
  run_constrained:
    - pytorch >=1.7,!=1.12.0
    - pyright >=1.1.280,<=1.1.320

test:
  imports:
    - maite
  requires:
    - pip
    - jupytext >= 1.14.0
    - numpydoc >= 1.5.0
    - pyright >= 1.1.280,<=1.1.320
    - pytest >= 7.0.0
    - hypothesis >= 6.61.0,<=6.113
    - pytest-mock >= 3.10.0
    - pytorch >=1.7,!=1.12.0
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/mit-ll-ai-technology/maite
  summary: Library of common types, protocols (a.k.a. structural subtypes), and utilities to support AI test and evaluation
  dev_url: https://github.com/mit-ll-ai-technology/maite
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jdarena66
    - leihamilton
    - myeesw
